routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/users');
});
Route::resource('users', 'UserController');

Route::get('/record/time','RecordTimeController@index');
Route::post('/record/time/get/details','RecordTimeController@getDetails');
Route::post('/record/time/save/details','RecordTimeController@saveDetails');

Route::get('/logs','LogController@index');
Route::post('/logs/get','LogController@getLogs');

app/Models/User.php
<?php
namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'email',
        'schedule',
        'contact'
    ];
    protected $table = 'users';

    /**
     * @return array
     */
    public static function getFields(){
        return [
            ['name' => 'first_name', 'label' => 'First Name', 'type' => 'text', 'required' => 1],
            ['name' => 'middle_name', 'label' => 'Middle Name', 'type' => 'text'],
            ['name' => 'last_name', 'label' => 'Last Name', 'type' => 'text'],
            ['name' => 'contact', 'label' => 'Contact', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => 1],
            ['name' => 'schedule', 'label' => 'Schedule', 'type' => ''],
        ];
    }

    /**
     * @return mixed|string
     */
    public function name(){
        $fullName = trim($this->first_name);
        if($this->middle_name != ''){
            $fullName .= ' '.trim($this->middle_name);
        }
        if($this->last_name != ''){
            $fullName .= ' '.trim($this->last_name);
        }
        return $fullName;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function hours()
    {
        return $this->hasMany(Hours::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Constants\Schedule;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'users' => User::all(),
            'scheduleTypes' => Schedule::TYPES
        ];

        return view('user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'fields' => User::getFields(),
            'scheduleTypes' => Schedule::TYPES
        ];

        return view('user.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'email' => 'required|email|unique:users',
        ]);
        User::create($request->except('_token'));
        return redirect('/users')->with('success', 'User is successfully saved');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'user' => User::findOrFail($id),
            'fields' => User::getFields(),
            'scheduleTypes' => Schedule::TYPES
        ];

        return view('user.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id
        ]);
        User::whereId($id)->update($request->except(['_token', '_method']));

        return redirect('/users')->with('success', 'User Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect('/users')->with('success', 'User is successfully deleted');
    }
}

resources/views/user/create.blade.php
<!-- create.blade.php -->
@extends('layout.index')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
        .form-group{
            padding: 10px;
        }
        .form-group.required label:after {
            content:"*";
            color:red;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Add User Form
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('users.store') }}">
                @csrf
                <div class="row">
                    @foreach($fields as $field)
                        <div class="form-group col-md-6 @if(isset($field['required'])) required @endif">
                            <label for="{{$field['name']}}">{{$field['label']}}</label>
                            @if($field['name'] == 'schedule')
                                <select class="form-control" name="{{$field['name']}}">
                                    @foreach($scheduleTypes as $typeIndex => $type)
                                        <option value="{{$typeIndex}}">{{$type}}</option>
                                    @endforeach
                                </select>
                            @else
                                <input type="{{$field['type']}}" class="form-control" name="{{$field['name']}}"/>
                            @endif

                        </div>
                    @endforeach

                    <div class="form-group col-12">
                        <button type="submit" class="btn btn-primary">Add User</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
<!-- update.blade.php -->
@extends('layout.index')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
        .form-group{
            padding: 10px;
        }
        .form-group.required label:after {
            content:"*";
            color:red;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit User Form
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('users.update', $user->id ) }}">
                @csrf
                @method('PATCH')
                <div class="row">
                    @foreach($fields as $field)
                        <div class="form-group col-md-6 @if(isset($field['required'])) required @endif">
                            <label for="{{$field['name']}}">{{$field['label']}}</label>
                                <?php $fieldName = $field['name']; ?>
                            @if($fieldName == 'schedule')
                                <select class="form-control" name="{{$fieldName}}">
                                    @foreach($scheduleTypes as $typeIndex => $type)
                                        <option value="{{$typeIndex}}">{{$type}}</option>
                                    @endforeach
                                </select>
                            @else
                                <input type="{{$field['type']}}" class="form-control" name="{{$field['name']}}" value="{{$user->$fieldName}}"/>
                            @endif

                        </div>
                    @endforeach

                    <div class="form-group col-12">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
<!-- index.blade.php -->
@extends('layout.index')

@section('content')
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br/>
    @endif
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Name</td>
            <td>Schedule</td>
            <td>Email</td>
            <td>Contact</td>
            <td></td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{$user->name()}}</td>
                <td>
                    @if(isset($scheduleTypes[$user->schedule]))
                        {{$scheduleTypes[$user->schedule]}}
                    @endif
                </td>
                <td>{{$user->email}}</td>
                <td>{{$user->contact}}</td>
                <td><a href="{{ route('users.edit', $user->id)}}" class="btn btn-primary">Edit</a></td>
                <td>
                    <form action="{{ route('users.destroy', $user->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection